#!/usr/bin/env python3
"""Add Stage 1 (Pretraining) and Stage 2 (Finetuning) cell blocks to Colab notebook."""

import json
import sys
from pathlib import Path

NOTEBOOK_PATH = Path("/Users/sehajroopbath/endo-seg/notebooks/swin_unetr_colab.ipynb")

# Define new cells to add
PRETRAINING_MARKDOWN = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 🎯 STAGE 1: Pretrain on Uterus + Ovary (3-class)\n",
        "\n",
        "**Objective:** Train a 3-class model (background, uterus, ovary) to learn:\n",
        "- Pelvic anatomy and MRI contrast patterns\n",
        "- Spatial context for where endometriomas occur\n",
        "- Progressive learning: large (uterus) → medium (ovary) → small (endo)\n",
        "\n",
        "**Dataset:** D2_TCPW - 49 training subjects (all have uterus, 39 have ovary)\n",
        "\n",
        "**Expected Performance:**\n",
        "- Uterus Dice > 0.90\n",
        "- Ovary Dice > 0.75\n",
        "- Convergence within 50-100 epochs\n",
        "\n",
        "**Why Pretrain?**\n",
        "1. Uterus/ovary available in 100%/80% of subjects (vs only 16% for endo)\n",
        "2. Encoder learns anatomical priors before tackling rare lesions\n",
        "3. Proven strategy for medical imaging (organ → lesion hierarchy)\n"
    ]
}

PRETRAINING_CODE = {
    "cell_type": "code",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# ============================================================================\n",
        "# STAGE 1: PRETRAIN ON UTERUS + OVARY (3-CLASS)\n",
        "# ============================================================================\n",
        "\n",
        "import copy\n",
        "\n",
        "# Create pretraining config (3-class: background, uterus, ovary)\n",
        "config_pretrain = copy.deepcopy(config)\n",
        "\n",
        "# Modify for pretraining\n",
        "config_pretrain.update({\n",
        "    \"num_classes\": 3,  # ✅ Only 3 classes\n",
        "    \"structures\": {\"uterus\": True, \"ovaries\": True, \"endometriomas\": False},  # ✅ No endo\n",
        "    \n",
        "    # Augmentation for pretraining\n",
        "    \"label_crop_config\": {\n",
        "        \"enabled\": True,\n",
        "        \"roi_size\": (224, 224, 96),\n",
        "        \"ratios\": [0.1, 0.4, 0.5],  # ✅ 10% bg, 40% uterus, 50% ovary\n",
        "        \"num_classes\": 3,\n",
        "        \"num_samples\": 4,\n",
        "        \"allow_smaller\": True,\n",
        "    },\n",
        "    \n",
        "    # Training params for pretraining\n",
        "    \"epochs\": 100,\n",
        "    \"learning_rate\": 2e-4,  # ✅ Slightly higher for training from scratch\n",
        "    \"batch_size\": 2,\n",
        "    \n",
        "    # Updated class weights for 3 classes\n",
        "    \"class_weights\": [0.01, 1.0, 3.0],  # [bg, uterus, ovary]\n",
        "    \"priority_classes\": [1, 2],  # Track both uterus + ovary\n",
        "    \n",
        "    # Loss function\n",
        "    \"loss_type\": \"dice_ce\",\n",
        "    \"use_generalized_dice\": False,\n",
        "    \"dice_weight\": 0.7,\n",
        "    \"ce_weight\": 0.3,\n",
        "    \n",
        "    # Subject sampling (less critical since most subjects have ovary)\n",
        "    \"subject_sampler_config\": {\n",
        "        \"enabled\": True,\n",
        "        \"ovary_weight\": 2.0,\n",
        "        \"default_weight\": 1.0,\n",
        "    },\n",
        "    \n",
        "    # Checkpoint directory\n",
        "    \"checkpoint_dir\": os.path.join(REPO_DIR, \"experiments\", \"checkpoints_pretrain\"),\n",
        "})\n",
        "\n",
        "print(\"\\n\" + \"=\"*80)\n",
        "print(\"🎯 STAGE 1: PRETRAINING ON UTERUS + OVARY (3-CLASS)\")\n",
        "print(\"=\"*80)\n",
        "print(f\"Num classes: {config_pretrain['num_classes']}\")\n",
        "print(f\"Structures: {config_pretrain['structures']}\")\n",
        "print(f\"Class weights: {config_pretrain['class_weights']}\")\n",
        "print(f\"Label crop ratios: {config_pretrain['label_crop_config']['ratios']}\")\n",
        "print(f\"Learning rate: {config_pretrain['learning_rate']}\")\n",
        "print(f\"Epochs: {config_pretrain['epochs']}\")\n",
        "print(\"=\"*80 + \"\\n\")\n",
        "\n",
        "# Update augmentation config\n",
        "augmentation_cfg_pretrain = dict(config_pretrain.get(\"augmentation_train\", {}))\n",
        "augmentation_cfg_pretrain[\"label_crop\"] = config_pretrain[\"label_crop_config\"]\n",
        "\n",
        "# Rebuild train transform\n",
        "from endo_seg.data.augment.transforms import get_train_transforms\n",
        "train_transform_pretrain = get_train_transforms(\n",
        "    augmentation_cfg_pretrain,\n",
        "    roi_size=config_pretrain[\"target_size\"]\n",
        ")\n",
        "\n",
        "# Rebuild datasets with 3-class structure\n",
        "seq_list_pretrain = [seq for seq, enabled in config_pretrain[\"sequences\"].items() if enabled]\n",
        "struct_list_pretrain = [struct for struct, enabled in config_pretrain[\"structures\"].items() if enabled]\n",
        "\n",
        "train_dataset_pretrain = EndoMRIDataset(\n",
        "    data_root=config_pretrain[\"dataset_dir\"],\n",
        "    subject_ids=splits[\"train\"],\n",
        "    sequences=seq_list_pretrain,\n",
        "    structures=struct_list_pretrain,\n",
        "    dataset_name=config_pretrain[\"pretrain_dataset\"],\n",
        "    preprocessor=preprocessor,\n",
        "    transform=train_transform_pretrain,\n",
        ")\n",
        "val_dataset_pretrain = EndoMRIDataset(\n",
        "    data_root=config_pretrain[\"dataset_dir\"],\n",
        "    subject_ids=splits[\"val\"],\n",
        "    sequences=seq_list_pretrain,\n",
        "    structures=struct_list_pretrain,\n",
        "    dataset_name=config_pretrain[\"pretrain_dataset\"],\n",
        "    preprocessor=preprocessor,\n",
        ")\n",
        "\n",
        "train_loader_pretrain = DataLoader(\n",
        "    train_dataset_pretrain,\n",
        "    batch_size=config_pretrain[\"batch_size\"],\n",
        "    shuffle=True,\n",
        "    num_workers=config_pretrain[\"num_workers\"],\n",
        "    pin_memory=True,\n",
        "    drop_last=True,\n",
        ")\n",
        "val_loader_pretrain = DataLoader(\n",
        "    val_dataset_pretrain,\n",
        "    batch_size=1,\n",
        "    shuffle=False,\n",
        "    num_workers=config_pretrain[\"num_workers\"],\n",
        "    pin_memory=True,\n",
        ")\n",
        "\n",
        "print(f\"Pretrain train batches: {len(train_loader_pretrain)}\")\n",
        "print(f\"Pretrain val batches: {len(val_loader_pretrain)}\")\n",
        "\n",
        "# Create 3-class model\n",
        "model_pretrain = SwinUNETRWithUncertainty(\n",
        "    in_channels=len(config_pretrain[\"sequences\"]),\n",
        "    out_channels=config_pretrain[\"num_classes\"],  # 3 classes\n",
        "    feature_size=config_pretrain[\"feature_size\"],\n",
        "    drop_rate=config_pretrain[\"drop_rate\"],\n",
        "    attn_drop_rate=config_pretrain[\"attn_drop_rate\"],\n",
        "    dropout_path_rate=config_pretrain[\"dropout_path_rate\"],\n",
        "    use_checkpoint=config_pretrain[\"use_checkpointing\"],\n",
        "    roi_size=config_pretrain[\"target_size\"],\n",
        "    sw_batch_size=config_pretrain[\"sw_batch_size\"],\n",
        "    infer_overlap=config_pretrain[\"infer_overlap\"],\n",
        "    device=device,\n",
        ").to(device)\n",
        "\n",
        "print(f\"\\n3-class model created with {sum(p.numel() for p in model_pretrain.parameters())/1e6:.2f}M params\\n\")\n",
        "\n",
        "# Run pretraining\n",
        "print(\"🚀 Starting Stage 1 pretraining...\\n\")\n",
        "history_pretrain = train_loop(\n",
        "    model=model_pretrain,\n",
        "    train_loader=train_loader_pretrain,\n",
        "    val_loader=val_loader_pretrain,\n",
        "    config=config_pretrain,\n",
        "    device=device,\n",
        ")\n",
        "\n",
        "print(\"\\n✅ Stage 1 pretraining complete!\")\n",
        "print(f\"Best checkpoint saved to: {os.path.join(config_pretrain['checkpoint_dir'], 'best.pth')}\")\n"
    ]
}

FINETUNING_MARKDOWN = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 🔬 STAGE 2: Finetune on Endometrioma (4-class with Transfer Learning)\n",
        "\n",
        "**Objective:** Transfer pretrained weights and finetune for 4-class segmentation\n",
        "\n",
        "**Transfer Learning Strategy:**\n",
        "1. Load pretrained encoder + decoder from Stage 1\n",
        "2. Expand final layer from 3 → 4 output channels\n",
        "3. Freeze early Swin transformer stages (0, 1)\n",
        "4. Finetune with extreme foreground bias on endometriomas\n",
        "\n",
        "**Key Adaptations:**\n",
        "- 70% endo-centered crops (vs 60% in basic training)\n",
        "- Focal loss for rare class emphasis\n",
        "- 15x class weight for endometrioma\n",
        "- Lower LR (5e-5) for finetuning\n",
        "- Longer patience (25 epochs)\n",
        "\n",
        "**Expected Performance:**\n",
        "- Endometrioma Dice > 0.55 (4x improvement from 0.139)\n",
        "- Ovary Dice > 0.70\n",
        "- Uterus Dice > 0.85\n"
    ]
}

TRANSFER_LEARNING_CODE = {
    "cell_type": "code",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# ============================================================================\n",
        "# HELPER FUNCTION: LOAD PRETRAINED MODEL AND EXPAND TO 4-CLASS\n",
        "# ============================================================================\n",
        "\n",
        "def load_pretrained_and_expand(\n",
        "    pretrained_checkpoint_path: str,\n",
        "    model_config: dict,\n",
        "    num_classes_new: int,\n",
        "    freeze_encoder_stages: list = [0, 1],\n",
        "    device: str = \"cuda\",\n",
        ") -> SwinUNETRWithUncertainty:\n",
        "    \"\"\"\n",
        "    Load pretrained 3-class model, expand to 4-class, and freeze early encoder.\n",
        "    \n",
        "    Args:\n",
        "        pretrained_checkpoint_path: Path to Stage 1 checkpoint\n",
        "        model_config: Config dict with model architecture params\n",
        "        num_classes_new: New number of classes (4)\n",
        "        freeze_encoder_stages: Which Swin stages to freeze (default [0,1])\n",
        "        device: Device to load model on\n",
        "    \n",
        "    Returns:\n",
        "        Model with pretrained weights, expanded output, and frozen encoder\n",
        "    \"\"\"\n",
        "    print(f\"\\n{'='*80}\")\n",
        "    print(\"🔄 TRANSFER LEARNING: Loading pretrained model and expanding to 4-class\")\n",
        "    print(f\"{'='*80}\\n\")\n",
        "    \n",
        "    # Load pretrained checkpoint\n",
        "    print(f\"Loading checkpoint from: {pretrained_checkpoint_path}\")\n",
        "    checkpoint = torch.load(pretrained_checkpoint_path, map_location=device)\n",
        "    pretrained_state = checkpoint[\"model_state\"]\n",
        "    print(f\"Loaded from epoch {checkpoint.get('epoch', 'unknown')} with Dice {checkpoint.get('score', 0):.4f}\")\n",
        "    \n",
        "    # Create new 4-class model\n",
        "    model_new = SwinUNETRWithUncertainty(\n",
        "        in_channels=len(model_config[\"sequences\"]),\n",
        "        out_channels=num_classes_new,  # 4\n",
        "        feature_size=model_config[\"feature_size\"],\n",
        "        drop_rate=model_config[\"drop_rate\"],\n",
        "        attn_drop_rate=model_config[\"attn_drop_rate\"],\n",
        "        dropout_path_rate=model_config[\"dropout_path_rate\"],\n",
        "        use_checkpoint=model_config[\"use_checkpointing\"],\n",
        "        roi_size=model_config[\"target_size\"],\n",
        "        sw_batch_size=model_config[\"sw_batch_size\"],\n",
        "        infer_overlap=model_config[\"infer_overlap\"],\n",
        "        device=device,\n",
        "    ).to(device)\n",
        "    \n",
        "    # Load pretrained weights (skip layers with shape mismatch)\n",
        "    model_dict = model_new.state_dict()\n",
        "    pretrained_dict = {\n",
        "        k: v for k, v in pretrained_state.items()\n",
        "        if k in model_dict and v.shape == model_dict[k].shape\n",
        "    }\n",
        "    \n",
        "    skipped_keys = set(model_dict.keys()) - set(pretrained_dict.keys())\n",
        "    print(f\"\\nLoaded {len(pretrained_dict)}/{len(model_dict)} layers from checkpoint\")\n",
        "    print(f\"Skipped {len(skipped_keys)} layers (shape mismatch or missing):\")\n",
        "    for key in sorted(skipped_keys):\n",
        "        print(f\"  - {key}\")\n",
        "    \n",
        "    model_dict.update(pretrained_dict)\n",
        "    model_new.load_state_dict(model_dict)\n",
        "    \n",
        "    # Freeze early Swin encoder stages\n",
        "    frozen_params = 0\n",
        "    total_params = 0\n",
        "    for name, param in model_new.named_parameters():\n",
        "        total_params += 1\n",
        "        # Freeze specified Swin stages\n",
        "        should_freeze = any(\n",
        "            f\"swinViT.layers.{stage}\" in name or f\"swinViT.layers_up.{stage}\" in name\n",
        "            for stage in freeze_encoder_stages\n",
        "        )\n",
        "        if should_freeze:\n",
        "            param.requires_grad = False\n",
        "            frozen_params += 1\n",
        "    \n",
        "    print(f\"\\nFroze {frozen_params}/{total_params} parameters in encoder stages {freeze_encoder_stages}\")\n",
        "    print(f\"Trainable parameters: {sum(p.numel() for p in model_new.parameters() if p.requires_grad)/1e6:.2f}M\")\n",
        "    print(f\"\\n{'='*80}\\n\")\n",
        "    \n",
        "    return model_new\n"
    ]
}

FINETUNING_CODE = {
    "cell_type": "code",
    "metadata": {},
    "execution_count": None,
    "outputs": [],
    "source": [
        "# ============================================================================\n",
        "# STAGE 2: FINETUNE ON ENDOMETRIOMA (4-CLASS)\n",
        "# ============================================================================\n",
        "\n",
        "import copy\n",
        "\n",
        "# Create finetuning config (4-class with transfer learning)\n",
        "config_finetune = copy.deepcopy(config)\n",
        "\n",
        "# Modify for finetuning\n",
        "config_finetune.update({\n",
        "    \"num_classes\": 4,  # ✅ All 4 classes\n",
        "    \"structures\": {\"uterus\": True, \"ovaries\": True, \"endometriomas\": True},  # ✅ Include endo\n",
        "    \n",
        "    # EXTREME foreground bias for endometriomas\n",
        "    \"label_crop_config\": {\n",
        "        \"enabled\": True,\n",
        "        \"roi_size\": (224, 224, 96),\n",
        "        \"ratios\": [0.05, 0.1, 0.15, 0.7],  # ✅ 70% endo-centered!\n",
        "        \"num_classes\": 4,\n",
        "        \"num_samples\": 8,  # ✅ Even more crops\n",
        "        \"allow_smaller\": True,\n",
        "    },\n",
        "    \n",
        "    # Finetuning training params\n",
        "    \"epochs\": 200,\n",
        "    \"learning_rate\": 5e-5,  # ✅ Lower LR for finetuning\n",
        "    \"weight_decay\": 1e-6,  # ✅ Less regularization\n",
        "    \"batch_size\": 2,\n",
        "    \"target_metric_patience\": 25,  # ✅ Longer patience\n",
        "    \n",
        "    # Aggressive class weights\n",
        "    \"class_weights\": [0.01, 0.5, 2.0, 15.0],  # ✅ 15x weight for endo!\n",
        "    \"priority_classes\": [2, 3],  # Ovary + endo\n",
        "    \n",
        "    # FOCAL LOSS for extreme class imbalance\n",
        "    \"loss_type\": \"focal\",  # ✅ Use FocalDiceCELoss\n",
        "    \"focal_gamma\": 2.0,\n",
        "    \"dice_weight\": 0.7,\n",
        "    \"focal_weight\": 0.3,\n",
        "    \n",
        "    # Aggressive subject sampling\n",
        "    \"subject_sampler_config\": {\n",
        "        \"enabled\": True,\n",
        "        \"endo_weight\": 6.0,  # ✅ High weight\n",
        "        \"ovary_weight\": 2.0,\n",
        "        \"default_weight\": 1.0,\n",
        "    },\n",
        "    \n",
        "    # Checkpoint directory\n",
        "    \"checkpoint_dir\": os.path.join(REPO_DIR, \"experiments\", \"checkpoints_finetune\"),\n",
        "})\n",
        "\n",
        "print(\"\\n\" + \"=\"*80)\n",
        "print(\"🔬 STAGE 2: FINETUNING ON ENDOMETRIOMA (4-CLASS)\")\n",
        "print(\"=\"*80)\n",
        "print(f\"Num classes: {config_finetune['num_classes']}\")\n",
        "print(f\"Structures: {config_finetune['structures']}\")\n",
        "print(f\"Class weights: {config_finetune['class_weights']}\")\n",
        "print(f\"Label crop ratios: {config_finetune['label_crop_config']['ratios']}\")\n",
        "print(f\"Loss type: {config_finetune['loss_type']}\")\n",
        "print(f\"Learning rate: {config_finetune['learning_rate']}\")\n",
        "print(f\"Epochs: {config_finetune['epochs']}\")\n",
        "print(\"=\"*80 + \"\\n\")\n",
        "\n",
        "# Load pretrained model and expand to 4-class\n",
        "pretrained_ckpt_path = os.path.join(\n",
        "    config_pretrain[\"checkpoint_dir\"],\n",
        "    \"best.pth\"\n",
        ")\n",
        "\n",
        "model_finetune = load_pretrained_and_expand(\n",
        "    pretrained_checkpoint_path=pretrained_ckpt_path,\n",
        "    model_config=config_finetune,\n",
        "    num_classes_new=4,\n",
        "    freeze_encoder_stages=[0, 1],  # Freeze first 2 Swin stages\n",
        "    device=device,\n",
        ")\n",
        "\n",
        "# Update augmentation config\n",
        "augmentation_cfg_finetune = dict(config_finetune.get(\"augmentation_train\", {}))\n",
        "augmentation_cfg_finetune[\"label_crop\"] = config_finetune[\"label_crop_config\"]\n",
        "\n",
        "# Rebuild train transform\n",
        "train_transform_finetune = get_train_transforms(\n",
        "    augmentation_cfg_finetune,\n",
        "    roi_size=config_finetune[\"target_size\"]\n",
        ")\n",
        "\n",
        "# Rebuild datasets with 4-class structure\n",
        "seq_list_finetune = [seq for seq, enabled in config_finetune[\"sequences\"].items() if enabled]\n",
        "struct_list_finetune = [struct for struct, enabled in config_finetune[\"structures\"].items() if enabled]\n",
        "\n",
        "train_dataset_finetune = EndoMRIDataset(\n",
        "    data_root=config_finetune[\"dataset_dir\"],\n",
        "    subject_ids=splits[\"train\"],\n",
        "    sequences=seq_list_finetune,\n",
        "    structures=struct_list_finetune,\n",
        "    dataset_name=config_finetune[\"pretrain_dataset\"],\n",
        "    preprocessor=preprocessor,\n",
        "    transform=train_transform_finetune,\n",
        ")\n",
        "val_dataset_finetune = EndoMRIDataset(\n",
        "    data_root=config_finetune[\"dataset_dir\"],\n",
        "    subject_ids=splits[\"val\"],\n",
        "    sequences=seq_list_finetune,\n",
        "    structures=struct_list_finetune,\n",
        "    dataset_name=config_finetune[\"pretrain_dataset\"],\n",
        "    preprocessor=preprocessor,\n",
        ")\n",
        "\n",
        "train_loader_finetune = DataLoader(\n",
        "    train_dataset_finetune,\n",
        "    batch_size=config_finetune[\"batch_size\"],\n",
        "    shuffle=True,\n",
        "    num_workers=config_finetune[\"num_workers\"],\n",
        "    pin_memory=True,\n",
        "    drop_last=True,\n",
        ")\n",
        "val_loader_finetune = DataLoader(\n",
        "    val_dataset_finetune,\n",
        "    batch_size=1,\n",
        "    shuffle=False,\n",
        "    num_workers=config_finetune[\"num_workers\"],\n",
        "    pin_memory=True,\n",
        ")\n",
        "\n",
        "print(f\"Finetune train batches: {len(train_loader_finetune)}\")\n",
        "print(f\"Finetune val batches: {len(val_loader_finetune)}\")\n",
        "\n",
        "# Run finetuning\n",
        "print(\"\\n🚀 Starting Stage 2 finetuning...\\n\")\n",
        "history_finetune = train_loop(\n",
        "    model=model_finetune,\n",
        "    train_loader=train_loader_finetune,\n",
        "    val_loader=val_loader_finetune,\n",
        "    config=config_finetune,\n",
        "    device=device,\n",
        ")\n",
        "\n",
        "print(\"\\n✅ Stage 2 finetuning complete!\")\n",
        "print(f\"Best checkpoint saved to: {os.path.join(config_finetune['checkpoint_dir'], 'best.pth')}\")\n",
        "\n",
        "# Plot both training histories\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
        "\n",
        "# Stage 1: Pretrain\n",
        "axes[0, 0].plot(history_pretrain[\"train_loss\"], label=\"Pretrain Loss\")\n",
        "axes[0, 0].set_title(\"Stage 1: Pretraining Loss\")\n",
        "axes[0, 0].set_xlabel(\"Epoch\")\n",
        "axes[0, 0].set_ylabel(\"Loss\")\n",
        "axes[0, 0].legend()\n",
        "\n",
        "axes[0, 1].plot(history_pretrain[\"val_epochs\"], history_pretrain[\"val_dice\"], marker=\"o\", label=\"Pretrain Dice\")\n",
        "axes[0, 1].set_title(\"Stage 1: Pretraining Validation Dice\")\n",
        "axes[0, 1].set_xlabel(\"Epoch\")\n",
        "axes[0, 1].set_ylabel(\"Dice\")\n",
        "axes[0, 1].legend()\n",
        "\n",
        "# Stage 2: Finetune\n",
        "axes[1, 0].plot(history_finetune[\"train_loss\"], label=\"Finetune Loss\")\n",
        "axes[1, 0].set_title(\"Stage 2: Finetuning Loss\")\n",
        "axes[1, 0].set_xlabel(\"Epoch\")\n",
        "axes[1, 0].set_ylabel(\"Loss\")\n",
        "axes[1, 0].legend()\n",
        "\n",
        "axes[1, 1].plot(history_finetune[\"val_epochs\"], history_finetune[\"val_dice\"], marker=\"o\", label=\"Finetune Mean Dice\")\n",
        "if history_finetune[\"priority_dice\"]:\n",
        "    axes[1, 1].plot(history_finetune[\"val_epochs\"], history_finetune[\"priority_dice\"], marker=\"x\", label=\"Priority Dice (Ovary+Endo)\")\n",
        "axes[1, 1].set_title(\"Stage 2: Finetuning Validation Dice\")\n",
        "axes[1, 1].set_xlabel(\"Epoch\")\n",
        "axes[1, 1].set_ylabel(\"Dice\")\n",
        "axes[1, 1].legend()\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.savefig(os.path.join(config_finetune[\"checkpoint_dir\"], \"training_history.png\"), dpi=150)\n",
        "plt.show()\n"
    ]
}

def main():
    """Add pretraining and finetuning blocks to notebook."""
    if not NOTEBOOK_PATH.exists():
        print(f"Error: Notebook not found at {NOTEBOOK_PATH}")
        return 1

    # Load notebook
    with open(NOTEBOOK_PATH) as f:
        nb = json.load(f)

    # Find insertion point (after the last training cell)
    # Looking for cell with run_stratified_training
    insert_idx = None
    for idx, cell in enumerate(nb["cells"]):
        if cell["cell_type"] == "code":
            source = "".join(cell.get("source", []))
            if "run_stratified_training" in source or "history = train_loop" in source:
                insert_idx = idx + 1

    if insert_idx is None:
        print("Warning: Could not find insertion point, appending to end")
        insert_idx = len(nb["cells"])

    # Insert new cells
    new_cells = [
        PRETRAINING_MARKDOWN,
        PRETRAINING_CODE,
        FINETUNING_MARKDOWN,
        TRANSFER_LEARNING_CODE,
        FINETUNING_CODE,
    ]

    for i, new_cell in enumerate(new_cells):
        nb["cells"].insert(insert_idx + i, new_cell)

    # Save updated notebook
    with open(NOTEBOOK_PATH, "w") as f:
        json.dump(nb, f, indent=1)

    print(f"✅ Added {len(new_cells)} new cells to notebook")
    print(f"   - 1 markdown cell (Stage 1 intro)")
    print(f"   - 1 code cell (Stage 1 pretraining)")
    print(f"   - 1 markdown cell (Stage 2 intro)")
    print(f"   - 1 code cell (Transfer learning helper)")
    print(f"   - 1 code cell (Stage 2 finetuning)")
    print(f"\nInserted at position {insert_idx}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
